//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dalaran.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories
    {
        public Categories()
        {
            this.SubCategories = new HashSet<SubCategories>();
        }
    
        public int CategoryId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SubCategories> SubCategories { get; set; }
    }
}
