//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dalaran.DAL
{
    using System.Collections.Generic;
    using Dalaran.DAL.Interfaces;
    public partial class Cities : IEntity
    {
        public Cities()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int CityId { get; set; }
        public string Name { get; set; }
        public int StateId { get; set; }
    
        public virtual States States { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}
