//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dalaran.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DalaranEntities : DbContext
    {
        public DalaranEntities()
            : base("name=DalaranEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Categories> Categories { get; set; }
        public DbSet<Cities> Cities { get; set; }
        public DbSet<Countries> Countries { get; set; }
        public DbSet<ProductDescriptions> ProductDescriptions { get; set; }
        public DbSet<ProductDescriptionTypes> ProductDescriptionTypes { get; set; }
        public DbSet<Products> Products { get; set; }
        public DbSet<States> States { get; set; }
        public DbSet<SubCategories> SubCategories { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
