//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dalaran.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.ProductDescriptions = new HashSet<ProductDescriptions>();
        }
    
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string UPC { get; set; }
        public string Condition { get; set; }
    
        public virtual ICollection<ProductDescriptions> ProductDescriptions { get; set; }
    }
}
