//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dalaran.DAL
{
    using System;
    using System.Collections.Generic;
    using Dalaran.DAL.Interfaces;
    public partial class ProductDescriptions : IEntity
    {
        public int ProductDescriptionId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ProductDescriptionTypeId { get; set; }
        public string Description { get; set; }
    
        public virtual ProductDescriptionTypes ProductDescriptionTypes { get; set; }
        public virtual Products Products { get; set; }
    }
}
