//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dalaran.DAL
{
    using System.Collections.Generic;
    using Dalaran.DAL.Interfaces;
    public partial class States : IEntity
    {
        public States()
        {
            this.Cities = new HashSet<Cities>();
        }
    
        public int StateId { get; set; }
        public string Name { get; set; }
        public int CountryId { get; set; }
    
        public virtual ICollection<Cities> Cities { get; set; }
        public virtual Countries Countries { get; set; }
    }
}
