//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dalaran.DAL
{
    using System;
    using Dalaran.DAL.Interfaces;
    public partial class Users : IEntity
    {
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Address { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Email { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> AccountState { get; set; }
    
        public virtual Cities Cities { get; set; }
    }
}
